runtime: python
env: flex
entrypoint: gunicorn -b :$PORT --chdir projetoTI/ projetoTI.wsgi:application

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.

beta_settings:
    cloud_sql_instances: unirent-316702:europe-west2:unirentpost-instance
#[END cloudsql_settings]

runtime_config:
  python_version: 3

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
